#!/bin/sh
#
#  pdns_recursor munin plugin.
#  Written by Sean Reifschneider <jafo@tummy.com> 2009-12-03
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_rec_*]' >/etc/munin/plugin-conf.d/pdns_rec
#    echo 'user root' >>/etc/munin/plugin-conf.d/pdns_rec
#
#  Configuration variables:
#
#    rec_control:    Path to rec_control executable
#                    (default: /usr/bin/rec_control)

REC_CONTROL="${rec_control:-/usr/bin/rec_control}"

if [ "$1" = "autoconf" ]; then
	if [ -e "$REC_CONTROL" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PDNS Recursor Answer Latency'
	echo 'graph_order latency'
	echo 'graph_vlabel usec'
	echo 'graph_info Question latency'
	echo 'graph_category pdns'
	echo 'graph_scale no'

	echo 'latency.label usec'
	echo 'latency.min 0'
	echo 'latency.type GAUGE'
	echo 'latency.info Answer latency'

	exit 0
fi

echo latency.value `"$REC_CONTROL" get qa-latency`
#VALUE=`"$REC_CONTROL" get qa-latency`
#printf 'latency.value %d.%06d\n' $[VALUE/1000000] $[VALUE%1000000]

exit 0
