#!/bin/sh
#
#  pdns_recursor munin plugin.
#  Written by Sean Reifschneider <jafo@tummy.com> 2009-12-03
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_rec_*]' >/etc/munin/plugin-conf.d/pdns_rec
#    echo 'user root' >>/etc/munin/plugin-conf.d/pdns_rec
#
#  Configuration variables:
#
#    rec_control:    Path to rec_control executable
#                    (default: /usr/bin/rec_control)

REC_CONTROL="${rec_control:-/usr/bin/rec_control}"

if [ "$1" = "autoconf" ]; then
	if [ -e "$REC_CONTROL" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PDNS Recursor Unauthorized'
	echo 'graph_order tcp udp unexpected'
	echo 'graph_vlabel queries'
	echo 'graph_info Unauthorized requests'
	echo 'graph_category pdns'

	echo 'tcp.label tcp'
	echo 'tcp.min 0'
	echo 'tcp.max 1000000'
	echo 'tcp.type DERIVE'
	echo 'tcp.info Unauthorized TCP queries'

	echo 'udp.label udp'
	echo 'udp.min 0'
	echo 'udp.max 1000000'
	echo 'udp.type DERIVE'
	echo 'udp.info Unauthorized UDP queries'

	echo 'unexpected.label unexpected'
	echo 'unexpected.colour ff0000'
	echo 'unexpected.min 0'
	echo 'unexpected.max 1000000'
	echo 'unexpected.type DERIVE'
	echo 'unexpected.info Unexpected queries (may indicate spoofing)'

	exit 0
fi

echo tcp.value `"$REC_CONTROL" get unauthorized-tcp`
echo udp.value `"$REC_CONTROL" get unauthorized-udp`
echo unexpected.value `"$REC_CONTROL" get unexpected-packets`

exit 0
